version: "3.9"
services:
  camcode-client:
    build:
      context: ./camcode-client
      dockerfile: ./Dockerfile-prod
    ports:
      - '443:4432'
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: ./Dockerfile-prod
    ports:
      - "3443:4432"
#docker-compose -f docker-compose-prod.yml up --build --progress=plain
